package com.qf.oa.dao;

import com.qf.oa.entity.DeptEmps;
import com.qf.oa.entity.Emp;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated
     */
    int insert(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated
     */
    int insertSelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated
     */
    Emp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Emp record);

    List<Emp> getEmpList();

    int deleteEmpandRoleInfo(Integer eid);
    int insertEmpandRoleInfo(@Param("eid") Integer eid, @Param("rids") Integer[] rids);

    Emp doLogin(@Param("email") String email);

    List<Emp> getEmpByKeyword(@Param("keyword") String keyword,@Param("id") Integer id);

    List<DeptEmps> getEmpNumByDept();

    List<DeptEmps> getEmpSexNum();

    int batchInsert(List<Emp> list);
}