package com.qf.oa.entity;

import java.io.Serializable;

public class Resc implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resc.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resc.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resc.repath
     *
     * @mbggenerated
     */
    private String repath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resc.restate
     *
     * @mbggenerated
     */
    private Integer restate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resc.redesc
     *
     * @mbggenerated
     */
    private String redesc;

    private boolean checked;

    public boolean isChecked() {
        return checked;
    }

    public void setChecked(boolean check) {
        this.checked = check;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_resc
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resc.id
     *
     * @return the value of t_resc.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resc.id
     *
     * @param id the value for t_resc.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resc.pid
     *
     * @return the value of t_resc.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resc.pid
     *
     * @param pid the value for t_resc.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resc.repath
     *
     * @return the value of t_resc.repath
     *
     * @mbggenerated
     */
    public String getRepath() {
        return repath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resc.repath
     *
     * @param repath the value for t_resc.repath
     *
     * @mbggenerated
     */
    public void setRepath(String repath) {
        this.repath = repath == null ? null : repath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resc.restate
     *
     * @return the value of t_resc.restate
     *
     * @mbggenerated
     */
    public Integer getRestate() {
        return restate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resc.restate
     *
     * @param restate the value for t_resc.restate
     *
     * @mbggenerated
     */
    public void setRestate(Integer restate) {
        this.restate = restate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resc.redesc
     *
     * @return the value of t_resc.redesc
     *
     * @mbggenerated
     */
    public String getRedesc() {
        return redesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resc.redesc
     *
     * @param redesc the value for t_resc.redesc
     *
     * @mbggenerated
     */
    public void setRedesc(String redesc) {
        this.redesc = redesc == null ? null : redesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resc
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Resc other = (Resc) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
            && (this.getRepath() == null ? other.getRepath() == null : this.getRepath().equals(other.getRepath()))
            && (this.getRestate() == null ? other.getRestate() == null : this.getRestate().equals(other.getRestate()))
            && (this.getRedesc() == null ? other.getRedesc() == null : this.getRedesc().equals(other.getRedesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resc
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getRepath() == null) ? 0 : getRepath().hashCode());
        result = prime * result + ((getRestate() == null) ? 0 : getRestate().hashCode());
        result = prime * result + ((getRedesc() == null) ? 0 : getRedesc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resc
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        return "Resc{" +
                "id=" + id +
                ", pid=" + pid +
                ", repath='" + repath + '\'' +
                ", restate=" + restate +
                ", redesc='" + redesc + '\'' +
                ", check=" + checked +
                '}';
    }
}