package com.qf.oa.entity;

import java.io.Serializable;

public class Role implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.rolename
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.roledesc
     *
     * @mbggenerated
     */
    private String roledesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.rolestate
     *
     * @mbggenerated
     */
    private Integer rolestate;
    private String repath;

    public String getRepath() {
        return repath;
    }

    public void setRepath(String repath) {
        this.repath = repath;
    }
/*   private List<Resc> rescList;

    public List<Resc> getRescList() {
        return rescList;
    }

    public void setRescList(List<Resc> rescList) {
        this.rescList = rescList;
    }*/

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.id
     *
     * @return the value of t_role.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.id
     *
     * @param id the value for t_role.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.rolename
     *
     * @return the value of t_role.rolename
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.rolename
     *
     * @param rolename the value for t_role.rolename
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.roledesc
     *
     * @return the value of t_role.roledesc
     *
     * @mbggenerated
     */
    public String getRoledesc() {
        return roledesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.roledesc
     *
     * @param roledesc the value for t_role.roledesc
     *
     * @mbggenerated
     */
    public void setRoledesc(String roledesc) {
        this.roledesc = roledesc == null ? null : roledesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.rolestate
     *
     * @return the value of t_role.rolestate
     *
     * @mbggenerated
     */
    public Integer getRolestate() {
        return rolestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.rolestate
     *
     * @param rolestate the value for t_role.rolestate
     *
     * @mbggenerated
     */
    public void setRolestate(Integer rolestate) {
        this.rolestate = rolestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Role other = (Role) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRolename() == null ? other.getRolename() == null : this.getRolename().equals(other.getRolename()))
            && (this.getRoledesc() == null ? other.getRoledesc() == null : this.getRoledesc().equals(other.getRoledesc()))
            && (this.getRolestate() == null ? other.getRolestate() == null : this.getRolestate().equals(other.getRolestate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRolename() == null) ? 0 : getRolename().hashCode());
        result = prime * result + ((getRoledesc() == null) ? 0 : getRoledesc().hashCode());
        result = prime * result + ((getRolestate() == null) ? 0 : getRolestate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        return "Role{" +
                "id=" + id +
                ", rolename='" + rolename + '\'' +
                ", roledesc='" + roledesc + '\'' +
                ", rolestate=" + rolestate +
                ", repath='" + repath + '\'' +
                '}';
    }
}